objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Death_Value__c</fullName>
        <label>Date of Death Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estate_and_Accrual__c</fullName>
        <label>Estate and Accrual</label>
        <referenceTo>EstateAcc__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BV_Case__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
                <value>
                    <fullName>Advertising (Internal)</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Advertising (External)</fullName>
                </value>
                <value>
                    <fullName>Awaiting Grant</fullName>
                </value>
                <value>
                    <fullName>Liquidation</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Put Away</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BV Case</label>
    <nameField>
        <label>BV Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BV Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BV_Case__c/fields/Net_Value__c.field-meta.xml
<CustomField>
    <fullName>Net_Value__c</fullName>
    <label>Net Value £</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/BV_Case__c/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <label>Advertising</label>
</RecordType>

force-app/main/default/objects/EstateAcc__c.object
<CustomObject>
    <fields>
        <fullName>BV_Case__c</fullName>
        <label>BV Case</label>
        <referenceTo>BV_Case__c</referenceTo>
        <relationshipName>EstateAccruals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Value__c</fullName>
        <label>Net Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Estate and Accrual</label>
    <nameField>
        <label>EstateAcc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estate and Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Liability__c.object
<CustomObject>
    <fields>
        <fullName>Estate_and_Accrual__c</fullName>
        <label>Estate and Accrual</label>
        <referenceTo>EstateAcc__c</referenceTo>
        <relationshipLabel>Liabilities</relationshipLabel>
        <relationshipName>Liabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Liability_at_Date_of_Death__c</fullName>
        <label>Liability at Date of Death</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Liability</label>
    <nameField>
        <label>Liability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EstateAccCalculationHandlerTest.cls
@isTest
public class EstateAccCalculationHandlerTest {
    @isTest
    static void testUpdateNetValue() {
        // Create test data: BV_Case
        BV_Case__c bvCase = new BV_Case__c(Stage__c = 'Advertising');
        insert bvCase;
        
        // Create test data: EstateAcc
        EstateAcc__c estateAcc = new EstateAcc__c(BV_Case__c = bvCase.Id);
        insert estateAcc;

        // Create test data: Asset
        Asset__c asset = new Asset__c(Estate_and_Accrual__c = estateAcc.Id, Date_Of_Death_Value__c = 2000);
        insert asset;
        
        // Create test data: Liability
        Liability__c liability = new Liability__c(Estate_and_Accrual__c = estateAcc.Id, Liability_at_Date_of_Death__c = 1000);
        insert liability;
        
        // Mock old values
        Map<Id, EstateAcc__c> oldEstateAccMap = new Map<Id, EstateAcc__c>{estateAcc.Id => estateAcc.clone()};
        
        // Modify values to trigger update
        asset.Date_Of_Death_Value__c = 3000;
        liability.Liability_at_Date_of_Death__c = 2000;
        
        // Call the method to test
        Test.startTest();
        EstateAccCalculationHandler.updateNetValue(new List<EstateAcc__c>{estateAcc}, oldEstateAccMap);
        Test.stopTest();
        
        // Retrieve the updated record
        EstateAcc__c updatedEstateAcc = [SELECT Net_Value__c FROM EstateAcc__c WHERE Id = :estateAcc.Id];
        
        // Assertions
        System.assertEquals(asset.Date_Of_Death_Value__c - liability.Liability_at_Date_of_Death__c, updatedEstateAcc.Net_Value__c);
    }
}