force-app/main/default/objects/BV_Case__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
                <value>
                    <fullName>Advertising (Internal)</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Advertising (External)</fullName>
                </value>
                <value>
                    <fullName>Awaiting Grant</fullName>
                </value>
                <value>
                    <fullName>Liquidation</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Put Away</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BV Case</label>
    <nameField>
        <label>BV Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BV Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Task__mdt.object
<CustomObject>
    <fields>
        <fullName>Assignee_Username__c</fullName>
        <label>Assignee Username</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date_Offset__c</fullName>
        <label>Due Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
                <value>
                    <fullName>Advertising (Internal)</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Advertising (External)</fullName>
                </value>
                <value>
                    <fullName>Awaiting Grant</fullName>
                </value>
                <value>
                    <fullName>Liquidation</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Put Away</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Stage Task</label>
    <pluralLabel>Stage Tasks</pluralLabel>
</CustomObject>

classes/BV_CaseTaskTriggerTest.cls
@isTest
private class BV_CaseTaskTriggerTest {

    @isTest static void testBVCaseUpdate() {

        // Insert a user for test assignment
        User testUser = new User(
            Alias = 'tuser',
            Email='testuser@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name='Standard User'].Id,
            TimeZoneSidKey='America/New_York',
            UserName='testuser' + String.valueOf(DateTime.now().getTime()) + '@testorg.com'
        );
        insert testUser;

        // Mocking Metadata
        Stage_Task__mdt mockMetadata = new Stage_Task__mdt(
            DeveloperName = 'Investigating_Task',
            Stage__c = 'Investigating',
            Due_Date_Offset__c = 3,
            Title__c = 'Investigating Task',
            Assignee_Username__c = testUser.Username,
            Mandatory__c = true
        );

        // Insert a BV_Case__c for testing
        BV_Case__c bvCase = new BV_Case__c(
            Name = 'Test BV Case',
            Stage__c = 'Receipt'
        );
        insert bvCase;

        // Update the BV_Case__c stage
        bvCase.Stage__c = 'Investigating';
        try {
            update bvCase;
            System.assert(false, 'Expected an exception because of the mandatory task.');
        } catch (Exception e) {
            System.assert(e.getMessage().contains('You need to complete the task: Investigating Task before moving to this stage.'));
        }
    }
}