force-app/main/default/objects/BV_Case__c.object
<CustomObject>
    <label>BV Case</label>
    <nameField>
        <label>BV Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BV Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BV_Case__c/fields/Current_Officer__c.field-meta.xml
<CustomField>
    <fullName>Current_Officer__c</fullName>
    <label>Current Officer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BV_Case__c/fields/Previous_1__c.field-meta.xml
<CustomField>
    <fullName>Previous_1__c</fullName>
    <label>Previous 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BV_Case__c/fields/Previous_2__c.field-meta.xml
<CustomField>
    <fullName>Previous_2__c</fullName>
    <label>Previous 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/BV_Case__c/fields/Previous_3__c.field-meta.xml
<CustomField>
    <fullName>Previous_3__c</fullName>
    <label>Previous 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Detail__c/Case_Detail__c.object-meta.xml
<CustomObject>
    <label>Case Detail</label>
    <nameField>
        <displayFormat>CD{000000}</displayFormat>
        <label>Case Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Detail__c/fields/BV_Case__c.field-meta.xml
<CustomField>
    <fullName>BV_Case__c</fullName>
    <label>BV Case</label>
    <referenceTo>BV_Case__c</referenceTo>
    <relationshipLabel>Case Details</relationshipLabel>
    <relationshipName>Case_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CaseOfficerController.cls
public with sharing class CaseOfficerController {
    @AuraEnabled(cacheable=false)
    public static Case_Detail__c getCaseDetail(String bvCaseId, String recordTypeId) {
        List<Case_Detail__c> caseDetails = [
            SELECT Id, Current_Officer__c, Previous_1__c, Previous_2__c, Previous_3__c, Date_Officer__c, Date_1_Officer__c 
            FROM Case_Detail__c 
            WHERE BV_Case__c = :bvCaseId AND RecordTypeId = :recordTypeId 
            LIMIT 1
        ];
        return caseDetails.size() > 0 ? caseDetails[0] : null;
    }
}