force-app/main/default/objects/BV_Case__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
                <value>
                    <fullName>Advertising (Internal)</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Advertising (External)</fullName>
                </value>
                <value>
                    <fullName>Awaiting Grant</fullName>
                </value>
                <value>
                    <fullName>Liquidation</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Put Away</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BV Case</label>
    <nameField>
        <label>BV Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BV Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BV_Case__c/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <label>Advertising</label>
</RecordType>

classes/BV_CaseTriggerHandlerTest.cls
@isTest
private class BV_CaseTriggerHandlerTest {

    static User createUser() {
        String randomString = String.valueOf(DateTime.now().getTime());
        User testUser = new User(
            Username = 'testuser' + randomString + '@example.com',
            Alias = 'tuser' + randomString.substring(8,11),
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = [SELECT Id FROM Profile WHERE Name='Standard User'].Id
        );
        insert testUser;
        return testUser;
    }

    @isTest
    static void testHandleTaskCreationForNewCases() {
        User testUser = createUser();
        
        BV_Case__c bvCase = new BV_Case__c(Stage__c = 'Receipt');
        insert bvCase;

        Test.startTest();
        BV_CaseTriggerHandler.handleTaskCreationForNewCases(new List<BV_Case__c> { bvCase });
        Test.stopTest();

        List<Task> tasks = [SELECT Id, Subject FROM Task WHERE WhatId = :bvCase.Id];
        System.assertEquals(true, tasks[0].Subject != null, 'Expected the task title to be non-null.');
    }

    @isTest
    static void testHandleTaskCreationOnUpdate() {
        User testUser = createUser();
        
        BV_Case__c bvCase = new BV_Case__c(Stage__c = 'Receipt');
        insert bvCase;
    
        bvCase.Stage__c = 'Advertising (Internal)';
    
        Exception actualException;
        try {
            update bvCase;
        } catch (Exception e) {
            actualException = e;
        }
    
        System.assertNotEquals(null, actualException, 'Expected an exception to be thrown.');
    }
}