force-app/main/default/objects/BV_Case__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
                <value>
                    <fullName>Advertising (Internal)</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Advertising (External)</fullName>
                </value>
                <value>
                    <fullName>Awaiting Grant</fullName>
                </value>
                <value>
                    <fullName>Liquidation</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>Put Away</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BV Case</label>
    <nameField>
        <label>BV Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BV Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BV_Case__c/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <label>Advertising</label>
</RecordType>

force-app/main/default/classes/TaskCreationQueueableTest.cls
@isTest
public class TaskCreationQueueableTest {

    @isTest
    static void testExecute() {
        // Create test data
        List<BV_Case__c> testCases = new List<BV_Case__c>();
        BV_Case__c testCase = new BV_Case__c(Stage__c = 'Advertising');
        insert testCase;
        testCases.add(testCase);

        Map<Id, BV_Case__c> oldMap = new Map<Id, BV_Case__c>();
        oldMap.put(testCase.Id, testCase);

        // Start Test
        Test.startTest();

        // Enqueue the queueable
        TaskCreationQueueable queueable = new TaskCreationQueueable(testCases, oldMap);
        System.enqueueJob(queueable);

        Test.stopTest();

        // Assert your results here
        // For example, query the tasks created and assert their existence
        List<Task> tasks = [SELECT Id FROM Task WHERE WhatId = :testCase.Id];
        System.assertEquals(3, tasks.size(), 'Expected three tasks to be created for the test case.');
    }
}