force-app/main/default/objects/EstateAcc__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Death_Summary__c</fullName>
        <label>Balance of Accruals</label>
        <summarizedField>Asset__c.Date_of_Death_Value__c</summarizedField>
        <summaryForeignKey>Asset__c.Estate_and_Accrual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Liability_at_Date_of_Death_Summary__c</fullName>
        <label>Balance of Liabilities</label>
        <summarizedField>Liability__c.Liability_at_Date_of_Death__c</summarizedField>
        <summaryForeignKey>Liability__c.Estate_and_Accrual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Net_Value__c</fullName>
        <label>Net Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Estate and Accrual</label>
    <nameField>
        <label>EstateAcc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estate and Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EstateAccCalculationHandler.cls
public class EstateAccCalculationHandler {
    public static void updateNetValue(List<EstateAcc__c> updatedEstateAccs, Map<Id, EstateAcc__c> oldEstateAccMap) {
        List<EstateAcc__c> estateAccsToUpdate = new List<EstateAcc__c>();

        for (EstateAcc__c estateAcc : updatedEstateAccs) {
            EstateAcc__c oldEstateAcc = oldEstateAccMap.get(estateAcc.Id);

            if (oldEstateAcc.Date_of_Death_Summary__c != estateAcc.Date_of_Death_Summary__c || 
                oldEstateAcc.Liability_at_Date_of_Death_Summary__c != estateAcc.Liability_at_Date_of_Death_Summary__c) {
                
                // Create a new instance of EstateAcc__c for update
                EstateAcc__c estateAccToUpdate = new EstateAcc__c(Id = estateAcc.Id);
                estateAccToUpdate.Net_Value__c = estateAcc.Date_of_Death_Summary__c - estateAcc.Liability_at_Date_of_Death_Summary__c;
                estateAccsToUpdate.add(estateAccToUpdate);
            }
        }

        if (!estateAccsToUpdate.isEmpty()) {
            update estateAccsToUpdate;
        }
    }
}